### ISSUE TITLE
Markt, Text wird blau wenn Name in Beschreibung vorkommt

### ISSUE THREAD

**Issue by Isitar** [etoa/etoa-gui#142]
https://github.com/etoa/etoa-gui/blob/9f5fbf4730eef3d17836fbc7bc31bfb260070221/htdocs/content/market/js.php#L1486

Fragt sich, ob das gewollt ist oder ein Bug. Wenn man in die Beschreibung beim Markt einen Namen rein tut, so erscheint dieses Angebot ebenfalls Blau, obwohl es nicht reserviert ist.

**Comment by river-etoa** [comment]
Hatte ich eingebaut, ist Absicht.
Die Spieler wünschten sich damals, in der langen Liste von Marktangeboten diejenigen hervorgehoben zu sehen, bei denen der eigene Nick in der Beschreibung steht. Weiss grad nicht mehr, obs damals noch keine Reservierung gab oder einfach die Leute Angebote reingestellt hatten "für Spieler X, und sonstwer falls Spieler X das doch nicht nimmt".
Ich würds drin lassen, ausser es stört irgendwie.
