### ISSUE TITLE
ReturnFactor Marktplatz

### ISSUE THREAD

**Issue by Isitar** [etoa/etoa-gui#145]
Der ReturnFactor vom Marktplatz ist etwas verwirrend. 

Konkretes Beispiel: Marktlevel 6
ReturnFactor wird berechnet aus 1 - 1/(MarktLevel+1), daraus ergibt sich: 0.85714....

Dargestellt wird er gerundet auf 2 Nachkommastellen, also 0.86
Zieht man nun das Angebot zurück (z.B. 100 Schiffe), so erhält man aber nur 85 zurück (weil 0.857 * 100 gibt 85.7 abgerundet ergibt sich 85).

Lösungsvorschlag:
Entweder 0.85 darstellen (und der User freut sich bei z.b. 1000 dass er 857 zurückerhält anstelle von 85) oder mit der dargestellten Zahl rechnen (also 0.86 zurückgeben in dem Falle)

Anpassung mit Aufrunden des Faktors: htdocs/content/own.php, und diverse andere ort (MarketHandler)
Anpassung der Darstellung: htdocs/market.php

**Comment by glaubinix** [comment]
Fixed with https://github.com/etoa/etoa-gui/pull/220
