### ISSUE TITLE
Use of undefined constant legal - assumed 'legal'

### ISSUE THREAD

**Issue by coo1ness** [etoa/etoa-gui#197]
Use of undefined constant legal - assumed 'legal' (this will throw an Error in a future version of PHP) in /var/lib/etoa/round20/htdocs/content/allianceboard.php on line 165"

**Comment by glaubinix** [comment]
Fixed with https://github.com/etoa/etoa-gui/commit/405e18ff5108a95eaef628d92234a9afcd25a68f already
