### ISSUE TITLE
Vorgonia Mysticum behält EXP

### ISSUE THREAD

**Issue by Ho-oi** [etoa/etoa-gui#204]
Wird ein Vorgonia Mysticum zerstört, werden nur die Level zurückgesetzt. Baut man es erneut, hat es dieselben EXP wie vor dessen Zerstörung.

**Comment by A-A-G** [comment]
Ist das nicht andersrum? Die Level bleiben und die Exp werden zurückgesetzt?

**Comment by glaubinix** [comment]
Fixed with https://github.com/etoa/etoa-gui/pull/221
