### ISSUE TITLE
Ausbau nicht möglich: "Fehlender Rohstoff 0t Titan"

### ISSUE THREAD

**Issue by lwihler** [etoa/etoa-gui#208]
**Kein Ausbau möglich obwohl die exakt genaue Anzahl Ress auf dem Plani liegt**

Jemand verschickt Ressourcen für Minen auf die Tonne genau und kann dann das Gebäude nicht klicken, weil das Spiel 'behauptet', es habe zu wenig Rohstoffe für den Ausbau (obwohl die Zahl exakt stimmt)

> Wenn die genau Anzahl Ressourcen auf einem Planeten für den Bau vorhanden ist, kann der Bau trotzdem nicht gestartet werden, da 0 Tonnen fehlen.
>Soweit ist dies auch nicht schlimm, weil man nach kurzer Zeit einfach im Menüpunkt Wirtschaft auf "neu Berechnen" klicken kann und somit das Problem umgangen wird. Jetzt bin ich leider an einem Punkt wo meine Speicher voll sind und somit auch nichts produziert wird.
> (Ich muss also 1 Tonne von dem fehlenden Rohstoff nachsenden).

**Comment by A-A-G** [comment]
Das liegt daran, dass die für den Bau notwendigen Ressourcen gerundet werden. Es wird also weniger angezeigt, als tatsächlich benötigt wird.
![image](https://user-images.githubusercontent.com/1158266/82120719-7905ef80-9788-11ea-96d9-687ab94ea098.png)
Die zum Bau notwendigen Ressourcen aufgerundet anzeigen sollte das Problem lösen.

**Comment by glaubinix** [comment]
Fixed with https://github.com/etoa/etoa-gui/pull/217
