### ISSUE TITLE
Sortierung der Schiffe in der Hilfe

### ISSUE THREAD

**Issue by lwihler** [etoa/etoa-gui#214]
Wenn man auf Hilfe > Schiffe klickt, und dort nach den verschiedenen Kriterien sortieren möchte, bringt ein Klick auf "Rasse" nicht das gewünschte Resultat hervor, bzw. wenn ich es richtig sehe, passiert einfach nichts, die Reihenfolge ändert nicht.

Für Runde 19:
https://round19.trantor.etoa.net/popup.php?page=help&site=shipyard&order=race_id

**Comment by Isitar** [comment]
es wird nach Rasse Sortiert, allerdings nicht alphabetisch nach rasse.
es wird nach rassen_id sortiert.

**Comment by A-A-G** [comment]
Dann sind die IDs aber komisch?
![image](https://user-images.githubusercontent.com/1158266/80094122-037e7900-8566-11ea-86c3-c33a02042c4b.png)

**Comment by Isitar** [comment]
ah ups, hab nur die ersten paar angeschaut, da hats noch gestimmt :)

**Comment by Isitar** [comment]
Liegt an folgender Zeile:
https://github.com/etoa/etoa-gui/blob/fff8f96eb458288d2e8064e36f01778313802cd7/htdocs/info/shipyard.php#L282

hier wird `ctype_alpha` auf den param gemacht, `race_id` ist allerdings nicht nur buchstaben (wegen dem _) --> gibt false zurück -> sortierung nach default.

**Comment by glaubinix** [comment]
https://github.com/etoa/etoa-gui/pull/218
