### ISSUE TITLE
Sonden ohne Piloten können in einem speziellen Fall nicht starten

### ISSUE THREAD

**Issue by Lukulus** [etoa/etoa-gui#215]
Es gibt einen Fall im dem man keine AINs oder Auroras starten kann, obwohl die Flottenkontrolle noch Slots hat und ausreichend Tritanium vorhanden ist.

Beispiel:
Eine Flotte mit Piloten landet auf einer Kolo, die ihr Bevölkerungsmaximum bereits erreicht hat. Durch die Piloten der Flotte sind nun mehr Bewohner auf der Kolo als nach Wohnmodul möglich. Das Wachstum wird nun Negativ.
Wenn der Spieler jetzt alle Bewohner (mehr als nach Wohnmodul wohnen können) in Bau- und Forschungsaufträge bindet, sterben Bewohner, die gebunden sind. Im System wird dann die Bevölkerungszahl negativ. Nun kann keine Flotte (auch keine AINs oder Auroras) mehr starten obwohl diese gar keine Piloten benötigen.

**Comment by glaubinix** [comment]
https://github.com/etoa/etoa-gui/pull/219
