### ISSUE TITLE
Abriss wird in Übersicht wie Ausbau dargestellt

### ISSUE THREAD

**Issue by lwihler** [etoa/etoa-gui#223]
**Beschreibung:**

Wenn ich auf einem Planeten ein Gebäude abreissen möchte, funktioniert das auf dem Planeten ganz gut. Sobald ich aber auf die Übersicht aller Planeten gehe, steht da die falsche Stufe.

![Screenshot_3](https://user-images.githubusercontent.com/38752973/82475144-55b2ab80-9acc-11ea-900c-634cd6fb7cc3.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/38752973/82475167-5e0ae680-9acc-11ea-9ed8-174552594a91.jpg)

**Comment by glaubinix** [comment]
https://github.com/etoa/etoa-gui/pull/224
