### ISSUE TITLE
Flottenstart trotz EMP möglich

### ISSUE THREAD

**Issue by Ho-oi** [etoa/etoa-gui#230]
Wenn der Raumhafen vor dem EMP Angriff aufgerufen wird, kann auch bei lahmgelegter Flottenkontrolle noch eine Flotte gestartet werden.

Beispiel:

13:00 - Raumhafen wird aufgerufen
13:02 - Raketen legen Flottenkontrolle bis 13:07 lahm
13:06 - Flotte wird gestartet.

Das hat in R20 und auf dem Testserver so funktioniert. Nicht getestet wurde, ob der Start per Favoriten noch möglich ist, solange die Seite nicht neu aufgerufen wird, und ob sich Werft/Fabrik/MP gleich verhalten.

**Comment by A-A-G** [comment]
Einfach in der FleetLaunch Klasse in launch() noch mal checkHaven() prüfen.

**Comment by A-A-G** [comment]
Markt benötigt keine Anpassung.
