### ISSUE TITLE
Allianz erstellen mit Leerzeichen

### ISSUE THREAD

**Issue by lwihler** [etoa/etoa-gui#235]
1) Es ist möglich, eine Allianz zu erstellen, indem man vier Leerschläge für den Tag und den Namen benutzt
(Das sollte nicht möglich sein)

2) Diese Allianz wird dann für andere Spieler (die keine Allianz haben) gelb angezeigt.

3) Wenn ich die Allianz umbenenne, wird sie für mich in der Statistik nicht mehr gelb angezeigt. (erst nach der Aktualisierung wieder)

PS: Es ist nicht möglich, eine Allianz in "Leerschläge" umzubenennen, dort kommt eine Fehlermeldung.

**Comment by A-A-G** [comment]
In `alliance.class.php` `create(..)` müsste man die Prüfungen von Name und Tag erweitern. Ich habe leider gerade keine Testumgebung. Vielleicht kann @ropeko das übernehmen. :)

**Comment by A-A-G** [comment]
Das PS kann ich nicht bestätigen?
![image](https://user-images.githubusercontent.com/1158266/110240491-6e515c80-7f4c-11eb-804c-ee0cc5bf65ea.png)

**Comment by mrcage** [comment]
Fixed by 4065ce3bf1fb4c0111c5d8fa3592ab1c81f9cd74
