### ISSUE TITLE
Technikbaum Sigma und Omega Verteidigung

### ISSUE THREAD

**Issue by lwihler** [etoa/etoa-gui#237]
![image](https://user-images.githubusercontent.com/38752973/116605687-03ab1480-a930-11eb-9990-c8833915603b.png)

Wird falsch angezeigt, obwohl in den Voraussetzungen alles richtig erfasst ist und nichts doppelt vorhanden ist.

**Comment by A-A-G** [comment]
Die Einträge in der Datenbank sind nicht korrekt. Das kann über das Admintool korrigiert werden:
Sigma: Waffenfabrik 12 entfernen und wieder hinzufügen.
Omega: Forschungslabor 7 entfernen und wieder hinzufügen.

Zumindest waren das bei mir die fehlerhaften Einträge. Zur Not einmal alle durchtesten. :D 

Ansonsten müsste jemand mit Datenbankzugriff mal draufschauen:
```
 select * from def_requirements where obj_id=4;
  select * from def_requirements where obj_id=8;
```

**Comment by glaubinix** [comment]
Fixed in Runde 21 und für zukünftige Runden behoben mit ab47582f6c7ed98d3b1aa842620fb1e65c65a8cd
