### ISSUE TITLE
lokales Login: Fehlermeldung bei Account registrieren

### ISSUE THREAD

**Issue by river-etoa** [etoa/etoa-gui#452]
`http://192.168.33.11/show/?index=register`

Account erstellen, kommt Meldung in Form eines Nachrichtenbalkens oben:

> **Error**
> Die Registration hat leider nicht geklappt: Expected response code 220 but got code "", with message ""

**Comment by river-etoa** [comment]
der User scheint trotzdem angelegt worden zu sein, erneutes Registrieren führt zur Meldung, dass der Nick schon existiert.

**Comment by glaubinix** [comment]
Registrierung läuft durch, aber das Senden der Email schlägt aktuell fehl. Wird behoben sobald die Show Seiten angepasst werden und wir dort einen null Transport einbauen.
