### ISSUE TITLE
Boost is not being calculated in global economy overview

### ISSUE THREAD

**Issue by mrcage** [etoa/etoa-gui#46]
Der Boost wird in der Wirtschaft-Gesamtübersicht nicht miteinberechnet, die richtige Produktion ist nur pro Planet zu sehen

**Comment by coo1ness** [comment]
Anscheinend werden in der Übersicht jetzt die Gesamtressourcen falsch zusammengerechnet. 
@isitar soll ich dir Zugang zum Testserver geben damit es besser überprüfen kannst?

**Comment by Isitar** [comment]
@coo1ness wäre hilfreich, so ins blaue hinaus zu programmieren ist immer schwierig

**Comment by coo1ness** [comment]
Ist erledigt.
