### ISSUE TITLE
Validate gas planet tritium production

### ISSUE THREAD

**Issue by mrcage** [etoa/etoa-gui#47]
Die Gasplaneten produzieren verhältnismässig zu wenig Tritium, was vermuten lässt, dass die Gomeisa Gassauger nicht zur Gesamtzahl der Gassauger gezählt wird. (Nur die Centauri Gassauger)

**Comment by glaubinix** [comment]
Fixed with https://github.com/etoa/etoa-gui/commit/9ae1907bb5b5b6a16c9dc04ab458fe9247c664a4
