### ISSUE TITLE
Admin-Tool - Rasse hinzufügen schlägt fehl

### ISSUE THREAD

**Issue by yaench** [etoa/etoa-gui#508]
Möchte man im Admin Tool eine neue Rasse erstellen und klickt auf "Neuen Datensatz speichern" erscheint ein HTTP Error 500 und die Rasse wird nicht hinzugefügt.

Im Admin Tool unter Datenbankfehler wird folgendes angezeigt:

> 22.04.2022 11:38:33, 176.127.114.26, [ADMIN]
> Database error
> 
> File: /var/www/etoa/htdocs/classes/dbmanager.class.php, line: 176
> 
> Query:
> 
> INSERT INTO races (`race_name`,`race_short_comment`,`race_comment`,`race_adj1`,`race_adj3`,`race_adj3`,`race_leadertitle`,`race_f_metal`,`race_f_crystal`,`race_f_plastic`,`race_f_fuel`,`race_f_food`,`race_f_power`,`race_f_population`,`race_f_researchtime`,`race_f_buildtime`,`race_f_fleettime`) VALUES('test','test','test','','','','','1','1','1','1','1','1','1','1','1','1');
> 
> Error Message:
> 
> **Column 'race_adj3' specified twice**
> 
> Stack-Trace:
> 
> #0 /var/www/etoa/htdocs/inc/functions.inc.php(50): DBManager->query('INSERT INTO rac...', 1)
> #1 /var/www/etoa/htdocs/admin/inc/advanced_forms.php(76): dbquery('INSERT INTO rac...')
> #2 /var/www/etoa/htdocs/admin/inc/admin_functions.inc.php(74): require_once('/var/www/etoa/h...')
> #3 /var/www/etoa/htdocs/admin/content/user.php(188): advanced_form('races', Object(Twig\Environment))
> #4 /var/www/etoa/htdocs/admin/index.php(150): include('/var/www/etoa/h...')
> #5 {main}

Workaround: Bestehende Rasse klonen, anpassen und speichern.

**Comment by glaubinix** [comment]
Fixed with https://github.com/etoa/etoa-gui/pull/511
