### ISSUE TITLE
Admin-Tool - Re:Discovery als Standarddesign führt zu weisser Seite

### ISSUE THREAD

**Issue by yaench** [etoa/etoa-gui#509]
Wird im Admin Tool als Standard Bildpaket und Standard Design das neue Re:Discovery Design konfiguriert, sehen die Spieler:innen nur noch eine weisse Seite nach der Anmeldung. Das Login funktioniert aber, die Session ist gültig und sichtbar im Admin Tool.
Vermutung: Der Doppelpunkt im Name des Designs führt zu einem Problem.

**Comment by glaubinix** [comment]
Die Konfiguration erwartet `Rediscovery` und nicht `Re:Discovery`
